#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: "Métodos de Física Matemática"
author: >
  <a href="mailto:lbarosi@df.ufcg.edu.br</a> ,
  Universidade Federal de Campina Grande, Brasil
copyright: '2025–2034'
logo: imgs/frontmatter/UAF_LOGO.png
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
# latex:
  # latex_documents:
  #   targetname: metodos_matematicos.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/barosil/METODOS_MATEMATICOS.git  # Use HTTPS em vez de SSH
  path_to_book: "livro"  # Mantenha como está se este for o caminho correto
  branch: main  # Mantenha como está


exclude_patterns:
  - .DS_Store
  - __pycache__

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - amsmath
    - deflist
    - html_image
    - amsmath
    - deflist
    - html_image
    - substitution


sphinx:
  extra_extensions:
    - sphinx_multitoc_numbering
    - sphinx_prolog.solex
    - sphinx_prolog.infobox
    - sphinx_prolog.swish
    - sphinx_prolog.pprolog
    - sphinx_proof
    - sphinx.ext.imgconverter
    - sphinx_copybutton


#######################################################################################
# HTML-specific settings
html:
  copybutton_prompt_text : r">>> |\.\.\. "
  copybutton_prompt_is_regexp : True
  copybutton_exclude : "style"
  html_theme: pydata_sphinx_theme
  theme: sphinx_book_theme  # The theme to use for HTML builds
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  # use_issues_button         : false  # Whether to add an "open an issue" button
  use_multitoc_numbering    : true   # Continuous numbering across parts/chapters
  extra_footer              : ""  # Will be displayed underneath the footer.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  # analytics:
  #   plausible_analytics_domain: ""
  #   plausible_analytics_url: "https://plausible.io/js/script.js"
  #   google_analytics_id       : ""  # A GA id that can be used to track book views.

  comments:
    hypothesis              : false
    utterances              : false
  announcement              : "" # A banner announcement at the top of the site.

#######################################################################################
# LaTeX-specific settings
# latex:
#   latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
#   use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
#   latex_documents:
#     targetname: metodos_matematicos.tex

#######################################################################################
# Launch button settings
# launch_buttons:
#   notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
#   binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
#   jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
#   thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
#   colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)
#   deepnote_url              : "" # The URL of Deepnote (https://deepnote.com)

    